[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.22"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
bsc = "https://bsc-dataseed.binance.org"
bsc_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545"
anvil = "http://localhost:8545"

[etherscan]
bsc = { key = "${BSCSCAN_API_KEY}" }
bsc_testnet = { key = "${BSCSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options 